[0m21:06:57.126811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc9eb7c1ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc9eb8ac620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc9eb8ccfb0>]}


============================== 21:06:57.262786 | 7ebfb136-ebd7-47f3-a458-52d8d1f83ec5 ==============================
[0m21:06:57.262786 [info ] [MainThread]: Running with dbt=1.9.1
[0m21:06:57.265821 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/dede1/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:07:11.378163 [debug] [MainThread]: Starter project path: /home/dede1/.cache/pypoetry/virtualenvs/ea-lh-EUHNUy7--py3.12/lib/python3.12/site-packages/dbt/include/starter_project
[0m21:07:11.392922 [info ] [MainThread]: 
Your new dbt project "banvic_dw" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:07:11.394902 [info ] [MainThread]: Setting up your profile.
[0m21:09:07.018772 [info ] [MainThread]: Profile banvic_dw written to /home/dede1/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:09:07.022919 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 125.217476, "process_in_blocks": "2696", "process_kernel_time": 0.769026, "process_mem_max_rss": "216548", "process_out_blocks": "67808", "process_user_time": 6.85972}
[0m21:09:07.025061 [debug] [MainThread]: Command `dbt init` succeeded at 21:09:07.024566 after 125.22 seconds
[0m21:09:07.027172 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc9eb4438f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc9cdd84440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc9ccd304d0>]}
[0m21:09:07.028492 [debug] [MainThread]: Flushing usage events
[0m21:09:07.595874 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:21:45.015069 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c643dd970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c6430b0e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c64f64860>]}


============================== 22:21:45.037815 | f522a7af-e832-473b-9010-668309372829 ==============================
[0m22:21:45.037815 [info ] [MainThread]: Running with dbt=1.9.1
[0m22:21:45.039533 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/dede1/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models gold.comercial.dim_data', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:21:45.040731 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/dede1/project/ea_lh/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:21:45.044035 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.15481022, "process_in_blocks": "54000", "process_kernel_time": 0.626067, "process_mem_max_rss": "87580", "process_out_blocks": "16", "process_user_time": 1.987516}
[0m22:21:45.045077 [debug] [MainThread]: Command `dbt run` failed at 22:21:45.044835 after 0.16 seconds
[0m22:21:45.045904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c646fe960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c676d7a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c647226f0>]}
[0m22:21:45.046633 [debug] [MainThread]: Flushing usage events
[0m22:21:45.659301 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:22:31.514523 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27c4ff7050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27c6a4b020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27c4d51c40>]}


============================== 22:22:31.521386 | 662cacff-eeb9-41ed-8f7b-82b1a0abf03c ==============================
[0m22:22:31.521386 [info ] [MainThread]: Running with dbt=1.9.1
[0m22:22:31.522556 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/dede1/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run --models gold.com.dim_data', 'send_anonymous_usage_stats': 'True'}
[0m22:22:31.523365 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/dede1/project/ea_lh/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:22:31.524858 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.16191345, "process_in_blocks": "0", "process_kernel_time": 0.220304, "process_mem_max_rss": "87560", "process_out_blocks": "8", "process_user_time": 2.155154}
[0m22:22:31.525742 [debug] [MainThread]: Command `dbt run` failed at 22:22:31.525548 after 0.16 seconds
[0m22:22:31.526458 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27c5d1f230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27c56839b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27c4ff7050>]}
[0m22:22:31.527118 [debug] [MainThread]: Flushing usage events
[0m22:22:32.011545 [debug] [MainThread]: An error was encountered while trying to flush usage events
